### ISSUE TITLE
CPAN Pull Request Challenge - Template-Semantic

### ISSUE THREAD

**Issue by nhainer** [tomill/Template-Semantic#12]
Hi,

I have been assigned by the 2015 CPAN Pull Request Challenge to offer my assistance in any of the following areas to the Template::Semantic distribution:

```
   Fixing bugs, if necessary
   Adding tests, if necessary
   Adding / correcting documentation, if necessary
   Adding CPAN conventions, if necessary
```

Would you please give me feedback regarding how I can be of best service to you?

Regards,

Neil Hainer

**Comment by tomill** [comment]
Thank you for this. we'll try on ... the next challenge :)
